<template>
  <div class="app">
    <header><div><small>COMFYUI · MINIMAX H3</small><h1>I2V 首帧生视频</h1><p>上传首帧图片与提示词，直接提交 MiniMax H3 I2V 工作流。</p></div><nav><a href="/?mode=storyboard">九宫格分镜生成</a><a class="active" href="/?mode=i2v">I2V 首帧生视频</a><a href="/?mode=director">多模式导演台</a><a href="/?mode=nine-images">九图分镜版</a><a href="/?mode=tasks">任务管理</a><a href="/?mode=system">系统信息</a></nav></header>
    <main class="layout">
      <section class="card form"><h2>生成设置</h2>
        <label>ComfyUI 服务地址<input v-model.trim="server" /></label>
        <label>首帧图片 <em>必选</em><input type="file" accept="image/*" @change="selectImage" /></label><img v-if="preview" :src="preview" class="preview" alt="首帧预览" />
        <label>提示词<textarea v-model="prompt" rows="10" /></label>
        <div class="params"><label>时长（秒）<input v-model.number="duration" type="number" min="2" max="15" step=".5" /></label><label>宽高比<select v-model="aspect"><option v-for="x in ratios" :key="x">{{ x }}</option></select></label><label>像素（MP）<input v-model.number="megapixels" type="number" min=".2" max="2" step=".1" /></label><label>对齐倍数<select v-model.number="multiple"><option :value="16">16</option><option :value="32">32</option><option :value="64">64</option></select></label></div>
        <button :disabled="running" @click="submit">{{ running ? '生成中…' : '生成视频' }}</button>
      </section>
      <section class="card result"><h2>任务状态</h2><p v-if="!job" class="muted">尚未提交任务。</p><template v-else><p><strong :class="job.status">{{ statusName }}</strong> <code>{{ job.id || '正在上传…' }}</code></p><pre>{{ job.log }}</pre><video v-if="job.video" :src="job.video" controls></video><a v-if="job.video" :href="job.video" target="_blank">打开 / 下载结果</a></template></section>
    </main>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import workflowTemplate from './assets/default_workflow.json'
const server=ref('http://192.168.8.231:8188'), image=ref(null), preview=ref(''), prompt=ref(''), duration=ref(5), aspect=ref('2:3 (Portrait Photo)'), megapixels=ref(.4), multiple=ref(32), running=ref(false), job=ref(null)
const ratios=['1:1 (Square)','2:3 (Portrait Photo)','3:2 (Landscape Photo)','4:5 (Portrait)','16:9 (Widescreen)']
const statusName=computed(()=>({uploading:'上传中',queued:'等待中',running:'生成中',completed:'已完成',error:'失败'}[job.value?.status]||'处理中'))
function selectImage(e){const f=e.target.files?.[0];if(f){image.value=f;preview.value=URL.createObjectURL(f)}}
async function upload(){const body=new FormData();body.append('image',image.value,image.value.name);body.append('overwrite','true');const r=await fetch(`${server.value}/upload/image`,{method:'POST',body});if(!r.ok)throw Error(`上传失败：HTTP ${r.status}`);return r.json()}
function workflow(name){const w=structuredClone(workflowTemplate);for(const node of Object.values(w)){if(node.class_type==='LoadImage')node.inputs.image=name;if(node.class_type==='MiniMaxH3ImageToVideo')node.inputs.prompt=prompt.value;if(node.class_type==='ResolutionSelector'){node.inputs.aspect_ratio=aspect.value;node.inputs.megapixels=megapixels.value;node.inputs.multiple=multiple.value}if(node.class_type==='PrimitiveFloat'&&node._meta?.title==='Float (duration)')node.inputs.value=duration.value}return w}
async function submit(){if(!image.value)return alert('请上传首帧图片');if(!prompt.value.trim())return alert('请填写提示词');running.value=true;job.value={status:'uploading',id:'',log:'正在上传首帧图片…',video:''};try{const file=await upload(),r=await fetch(`${server.value}/prompt`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:workflow(file.name)})}),data=await r.json();if(!r.ok||data.error)throw Error(data.error?.message||data.error||`提交失败：HTTP ${r.status}`);job.value={status:'queued',id:data.prompt_id,log:`任务已提交：${data.prompt_id}`,video:''};poll()}catch(e){job.value.status='error';job.value.log+=`\n错误：${e.message}`;running.value=false}}
async function poll(){try{const r=await fetch(`${server.value}/history/${job.value.id}`),data=await r.json(),entry=data[job.value.id];if(!entry){job.value.status='queued';job.value.log+='\n等待 GPU 调度…'}else if(entry.status?.status_str==='error')throw Error('ComfyUI 执行失败');else if(entry.status?.completed){job.value.status='completed';job.value.video=output(entry.outputs||{});job.value.log+=job.value.video?'\n视频已生成。':'\n执行完成，但未找到视频输出。';running.value=false;return}else{job.value.status='running';job.value.log+='\n正在生成…'}setTimeout(poll,2500)}catch(e){job.value.status='error';job.value.log+=`\n错误：${e.message}`;running.value=false}}
function output(outputs){for(const node of Object.values(outputs))for(const key of ['images','gifs','videos']){const f=node[key]?.find(x=>x.filename);if(f)return `${server.value}/view?${new URLSearchParams({filename:f.filename,subfolder:f.subfolder||'',type:f.type||'output'})}`}return ''}
</script>

<style scoped>
:global(:root){font-family:Inter,system-ui,"Microsoft YaHei",sans-serif;color:#e7edf7;background:#101825}:global(body){margin:0}.app{max-width:1200px;margin:auto;padding:30px}header{display:flex;justify-content:space-between;gap:20px;margin:10px 0 28px}small{color:#7dd3fc;letter-spacing:.12em;font-weight:700}h1{margin:8px 0;font-size:32px}h2{margin:0 0 12px;font-size:18px}header p,.muted{color:#9eb0cb;margin:0}nav{display:flex;gap:8px;height:max-content;flex-wrap:wrap}nav a{color:#c9d5e7;text-decoration:none;padding:8px 11px;border:1px solid #2a3a53;border-radius:8px;font-size:13px;white-space:nowrap}nav a.active{color:#062034;background:#67e8f9;border-color:#67e8f9}.layout{display:grid;grid-template-columns:430px 1fr;gap:20px}.card{background:#172233;border:1px solid #2a3a53;border-radius:16px;padding:22px;box-shadow:0 16px 40px #0002}label{display:block;color:#c9d5e7;font-size:13px;font-weight:600;margin-top:14px}em{color:#fbbf24;font-style:normal}input,select,textarea{width:100%;margin-top:7px;color:#ecf5ff;background:#0f1725;border:1px solid #3a4e6d;border-radius:8px;padding:10px;font:inherit}textarea{resize:vertical}.params{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.preview{width:100%;max-height:250px;object-fit:contain;margin-top:10px;background:#0b1019;border:1px solid #3a4e6d;border-radius:10px}button{width:100%;margin-top:20px;border:0;padding:13px;border-radius:10px;font-size:15px;font-weight:700;color:#062034;background:linear-gradient(90deg,#67e8f9,#38bdf8);cursor:pointer}button:disabled{opacity:.55;cursor:wait}strong{padding:5px 10px;border-radius:99px;font-size:12px}.uploading,.queued{color:#fde68a;background:#41381d}.running{color:#7dd3fc;background:#173c55}.completed{color:#86efac;background:#163827}.error{color:#fca5a5;background:#4b2029}code{margin-left:10px;color:#c9d5e7;font-size:12px;word-break:break-all}pre{white-space:pre-wrap;background:#0d1420;border:1px solid #293950;padding:12px;border-radius:8px;font-size:12px;max-height:180px;overflow:auto}.result video{display:block;width:100%;background:#000;border-radius:10px;margin-top:14px}.result a{display:inline-block;margin-top:12px;color:#7dd3fc}@media(max-width:800px){.app{padding:18px}header{display:block}nav{margin-top:14px}.layout{grid-template-columns:1fr}.params{grid-template-columns:1fr}}
</style>
